# tryCatch

tryCatch runs the function passed to it and returns its return value if
everything goes right. If an error is thrown, it calls the error handler passed
to it and returns its return value

### Import

```typescript copy
import { tryCatch } from '@fullstacksjs/toolbox';
```

### Signature

```typescript copy
function tryCatch<T, E>(
  fn: (...args: any[]) => T,
  onError: (err: unknown) => E,
): E | T;
```

### Examples

If there are no errors:

```typescript copy
const execute = () => {
  return 'ok';
};

const handler = (err: unknown) => {
  return 'Parsed Error';
};

tryCatch(execute, handler); // 'ok'
```

If there is an error:

```typescript copy
const execute = () => {
  throw 'Unknown Error';
};

const handler = (err: unknown) => {
  return 'Parsed Error';
};

tryCatch(execute, handler); // 'Parsed Error'
```
